### ISSUE TITLE
No update since 3weeks

### ISSUE THREAD

**Issue by nil0x42** [SecOps-Institute/Akamai-ASN-and-IPs-List#2]
Hi ! I noticed that the list have not been updated since 3weeks, the bot might be broken.

Thank you for your amazing repo !

**Comment by aarvee11** [comment]
Apologies. We ran out of funds and hence took a coffee break.

We shall resume the feed by 29th Feb 2024. 

Thank you for the patience, trust and  support!

**Comment by aarvee11** [comment]
Please check now. Still the lists are not getting updated hourly as done previously. Working on the same

**Comment by nil0x42** [comment]
Nice, thank you ! It's working fine
